---
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: go build -o ./termpicker -v ./cmd/termpicker
      - name: Test
        run: go test -v ./...
      - name: VHS Gif update
        uses: charmbracelet/vhs-action@v1
        with:
          path: assets/demo.tape
      - name: Commit and push updated GIF demo
        run: |-
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./assets/demo.gif README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m 'Update GIF preview in README'
            git push
          fi
